services:
  frontend:
    image: noor009/chatpulse-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - chat-network
    restart: unless-stopped

  backend:
    image: noor009/chatpulse-backend:latest
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - backend/.env
    networks:
      - chat-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data:







