apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w3 mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
        - name: chatapp-backend
          image: abdullahbinamin/chatapp-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: "production"  
            - name: PORT
              value: "5001"
            - name: MONGODB_URI
              value: "mongodb://root:root@mongodb:27017/chatapp?authSource=admin&retryWrites=true&w=majority"
            - name: CORS_ORIGIN
              value: "http://abdullahbinamin.qzz.io"
            - name: COOKIE_SECURE
              value: "false"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              value: "7d"
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: CLOUDINARY_API_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
