apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data: 
  JWT_SECRET: MklHTmlPU1p1VUFDd2w0bU1oZTBZcjhkb3lwekxBNlBBc2tUSm9qOXBmSA==
  CLOUDINARY_CLOUD_NAME: cGxhY2Vob2xkZXI=
  CLOUDINARY_API_KEY: cGxhY2Vob2xkZXI=
  CLOUDINARY_API_SECRET: cGxhY2Vob2xkZXI=